name: nextjsapplication

on: 
 push:
   branches: [ main ]

jobs:
  automated-next-js:
             runs-on: ubuntu-latest

             steps:
              - name: checkout-changes
                uses: actions/checkout@v5.0.0
              - name: nodejs-setup
                uses: actions/setup-node@v5.0.0
                with:
                  node-version: 22.x
                  cache: 'npm'
              - name: install dependencies
                working-directory: APP
                run: npm install
              - name: make build
                run: npm run build
              - name: build using artifacts
                uses: actions/upload-artifact@v4.6.2
                with: 
                 name: Next js build
                 path: out/
                
     
